# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171026_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartsalesman',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cartsalesman',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='ordersalesman',
            options={'ordering': ['name'], 'verbose_name': 'Ordem Vendor', 'verbose_name_plural': 'Ordens Vendedores'},
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartSalesman',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
