# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20171104_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateEnd',
            field=models.DateTimeField(null=True, verbose_name='Data Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='valueTotal',
            field=models.IntegerField(null=True, verbose_name='Valor Total'),
        ),
    ]
