# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20171104_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='value',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='valueTotal',
            field=models.FloatField(default=0, null=True, verbose_name='Valor Total'),
        ),
    ]
