# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20171111_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateEnd',
            field=models.DateField(null=True, verbose_name='Data Entrega'),
        ),
    ]
