# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20171122_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Comprando'), (1, 'Finalizada'), (2, 'Fabricar'), (3, 'Entregue')], default=0, verbose_name='Status'),
        ),
    ]
