# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://res.cloudinary.com/graphic/image/upload/v1510583520/user-default_temkoq.jpg', max_length=350, verbose_name='Foto'),
        ),
    ]
