# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171113_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://res.cloudinary.com/graphic/image/upload/v1510588337/User/user-default.jpg', max_length=350, verbose_name='Foto'),
        ),
    ]
