# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171115_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.IntegerField(choices=[(0, 'padrao'), (1, 'campo'), (2, 'vinho')], default=0, verbose_name='Tema'),
        ),
    ]
