# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20171021_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('salesMan', models.CharField(blank=True, max_length=150, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Fabricacao de Produto',
                'ordering': ['name'],
                'verbose_name_plural': 'Fabricacao de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('size', models.CharField(max_length=30, verbose_name='Tamanho')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('acquiredValue', models.IntegerField(verbose_name='Valor de Frabricacao')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('saleValue', models.IntegerField(verbose_name='Valor de Venda')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'ordering': ['name'],
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddField(
            model_name='factoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Produto'),
        ),
    ]
