# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='acquiredValue',
            field=models.IntegerField(blank=True, verbose_name='Valor de Frabricacao'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
