# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171022_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='acquiredValue',
            field=models.IntegerField(blank=True, default=0, verbose_name='Valor de Frabricacao'),
        ),
    ]
