# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_galleryproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryproducts',
            name='img',
            field=models.CharField(default='https://res.cloudinary.com/graphic/image/upload/v1510583427/product-default_tifjsl.jpg', max_length=350, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='galleryproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Produto'),
        ),
    ]
