# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171113_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryproducts',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='galleryproducts',
            name='status',
            field=models.IntegerField(choices=[(0, 'activated'), (1, 'disabled')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='galleryproducts',
            name='img',
            field=models.CharField(max_length=350, verbose_name='Imagem'),
        ),
    ]
