# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171115_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryproducts',
            name='number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
    ]
