# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171115_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgDefault',
            field=models.CharField(default=0, max_length=350, verbose_name='Imagem Padrão'),
        ),
    ]
