# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20171115_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgDefault',
            field=models.CharField(default='none', max_length=350, verbose_name='Imagem Padrão'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
